platform/windows/templates/sweepminer/main.cpp

- Replace 'and' with '&&' because 'and' does not always work. 
- Fix index out of bound issue though the compiler doesn't check it.

[fix] fix issue in mine sweep template

---

packages/appimage/dockerfile-aarch64/Dockerfile
packages/appimage/dockerfile-riscv64/Dockerfile
packages/appimage/dockerfile-x86_64/Dockerfile

Fix input under KDE Plasma Wayland with [Fcitx 5’s recommended configuration](https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma).

Enable Wayland support in AppImage

---

.gitattributes
addon/compiler_hint/debian.tl
addon/gen.sh
packages/debian/01-in-docker.sh
packages/debian/builddeb.sh
packages/debian/compiler_hint.lua
packages/debian/control
packages/debian/rules

Also add compatible terminals to recommends. By default `apt install` will install qterminal if no compatible terminal installed.

Add MinGW support to deb amd64

---

.github/workflows/build.yml

Ref. https://github.com/containers/podman/issues/21012

Workaround chmod failures in containerized CI build

---

packages/msys/build-i686.sh
packages/msys/build-x64.sh

- make it machine-independent
- simplify 7z package
- fail fast

Update msys packaging scripts

---

RedPandaIDE/resources/colorschemes/MoLo_CBLight.scheme

Pure foreground highlighted words and bracket matching

Try new features on MoLo CBLight

---

platform/windows/installer-scripts/redpanda.nsi

- installer language is no longer remembered (shell context not decided yet when choosing language)

Add per-user installation

---

packages/archlinux/PKGBUILD.in

Required by weston compositor.

Add rasterized icons in Arch Linux package

---

RedPandaIDE/compiler/sdccprojectcompiler.cpp

sdcc makefile生成优化

---

RedPandaIDE/resources/colorschemes/MoLo_Mia.scheme

1.可满足MoLo主题复制到白纸的需求，例如实验报告。
2.可配合浅色主题作为常规的浅色配色使用。

Add color scheme MoLo Mia

---

platform/windows/installer-scripts/utils.nsh

Windows ME (3000) > Windows XP (2600)

Check whether NT in windows installer

---

platform/linux/templates/epitrochoid/epitrochoid_c.txt
platform/linux/templates/epitrochoid/epitrochoid_zh_CN.c
platform/linux/templates/hypotrochoid/hypotrochoid_c.txt
platform/windows/templates/epitrochoid/epitrochoid_c.txt
platform/windows/templates/epitrochoid/epitrochoid_zh_CN.c
platform/windows/templates/hypotrochoid/hypotrochoid_c.txt
platform/windows/templates/raygui/raygui_c.txt

The version of raygui has been upgrade to 4.0 and raylib upgrade to 5.0 in 3.0 release package, there are some broken changes in the raygui API that need to be fixed.

Update the raygui examples due to the upgrade of raygui and raylib version

---

RedPandaIDE/resources/terminal-unix.json
RedPandaIDE/settings.cpp
RedPandaIDE/utils.cpp
packages/debian-static/control.in
packages/debian/control

Launch Linux terminal in its own process

---

RedPandaIDE/RedPandaIDE.pro
RedPandaIDE/main.cpp
RedPandaIDE/utils.cpp
RedPandaIDE/utils.h
RedPandaIDE/xmake.lua
libs/qsynedit/qsynedit.pro
libs/qsynedit/xmake.lua
libs/redpanda_qt_utils/redpanda_qt_utils.pro
libs/redpanda_qt_utils/xmake.lua
xmake.lua

Reverts royqh1979/RedPanda-CPP#449

Revert "Use Qt resource system's recommended approach for translation files"

---

RedPandaIDE/resources/colorschemes/MoLo_CBLight.scheme
RedPandaIDE/resources/colorschemes/MoLo_CodeBlack.scheme
RedPandaIDE/resources/colorschemes/MoLo_Mia.scheme

MoLo CBLight
尝试低饱和特殊数和活动断点内元素区分
MoLo Mia
优化空白字符在断点内的显示
MoLo CodeBlack
统一使用新的空白字符、断点、活动断点

Update MoLo series color schemes

---

RedPandaIDE/editor.cpp
RedPandaIDE/mainwindow.cpp
RedPandaIDE/settings.cpp
RedPandaIDE/settingsdialog/formattergeneralwidget.cpp
RedPandaIDE/utils.cpp
RedPandaIDE/utils.h

- The format of `LANG` varies between platforms. Do not set it.
- Do not capture stderr of astyle process.

Fix AStyle locale

---

.github/workflows/build.yml
BUILD.md
BUILD_cn.md
packages/msys/build-llvm.sh
packages/msys/build-mingw.sh

- mingw-w64-clang-i686-qt5-static removed
- mingw-w64-i686-7zip removed

Update Windows packaging script: follow upstream MSYS2 changes

---

RedPandaIDE/RedPandaIDE.pro
RedPandaIDE/settingsdialog/environmentappearancewidget.cpp
RedPandaIDE/translations/RedPandaIDE_ru_RU.ts

- Update interface localization file RedPandaIDE_ru_RU.ts
- Add qtbase_ru_RU in project file with checking by exists()

Update Russian translation

---

tools/consolepauser/consolepauser.pro
tools/consolepauser/main.windows.cpp
tools/consolepauser/xmake.lua

- Also use console API instead of stdio to avoid charset conversion

Use wide API in Windows console pauser

---

.github/workflows/build.yml
packages/fedora/buildrpm.sh
packages/macos/build.sh
packages/opensuse/buildrpm.sh

- Remove old versions
- Workaround Fedora sudo change

Fix CI build

---

.github/workflows/build.yml
README.md

Avoid auto build actions for md files, etc.

---

RedPandaIDE/parser/cppparser.cpp
RedPandaIDE/widgets/classbrowser.cpp

Bugfix anonymous namespace
