royqh1979/RedPanda-CPP

RedPandaIDE/compiler/executablerunner.cpp, RedPandaIDE/compiler/ojproblemcasesrunner.cpp
When running the compiled user program, current compiler's binary directories should be added to the beginning of the Path environment variable instead of the end, in order to avoid loading other user-installed versions of MinGW libraries (such as libstdc++). Otherwise, weird behaviors occur when the user has installed a lower version of libstdc++ and add it to system Path. And this only affects a subset of user programs that use library routines with their ABI changed. Moreover, RedPanda uses brand new GCC compiler, which increases the chance that the user has a incompatible version elsewhere (maybe in hidden locations such as an Anaconda installation). 
The above problem was discovered on a setup of my friend's environment  @coldbubbletea
Previously, in openShell of mainwindow.cpp the …
=> make behavior consistent in adding compiler bindirs to Path

RedPandaIDE/settings.cpp, RedPandaIDE/settings.h
Parse CPU field from target triplet and determine bitness from it.
Tested on [Tencent Cloud VM ARM64 instance](https://cloud.tencent.com/document/product/213/11518#SR1), Debian 11.
<hr>
```cpp
if (baseSet->target().contains("64") || baseSet->target() == "s390x")
```
According to [an incomplete list of triplets](https://gcc.gnu.org/install/specific.html), targets that contain “64” seem to be 64-bit targets without any exception. “s390x” is the only 64-bit target I found that does not contain “64”.
=> Handle non-x86 64-bit targets

RedPandaIDE/settings.cpp, RedPandaIDE/settings.h
Programs enabling Address Sanitizer (ASan) would cost several seconds after `main` on non-x86 64-bit architectures. My test shows that a hello world program took ~3s on Ampere Altra (Cloud VM) and ~6s on AllWinner H6 (development board).
[File structure of LLVM’s implementation of ASan](https://github.com/llvm/llvm-project/tree/main/compiler-rt/lib/asan), which is also [GCC’s implementation](https://github.com/gcc-mirror/gcc/tree/master/libsanitizer/asan), shows that the runtime library `asan_rtl` optimization only applies to x86-64, and other arches share the general, unoptimized one. Since address space of 64-bit apps is extremely large, the sanitizing check may cost long time.
In this patch, some extra checks are added to determine whether enable ASan or not:
- always enable on x86-64 …
=> Disable Address Sanitizer on non-x86 64-bit Linux

BUILD.md, BUILD_cn.md, RedPandaIDE/compiler/compilermanager.cpp, RedPandaIDE/debugger.cpp, RedPandaIDE/mainwindow.cpp, RedPandaIDE/settings.cpp, RedPandaIDE/settings.h, RedPandaIDE/utils.h, packages/appimage/01-in-docker.sh, packages/appimage/build-aarch64.ps1, packages/appimage/build-aarch64.sh, packages/appimage/build-x86_64.ps1, packages/appimage/build-x86_64.sh, packages/appimage/dockerfile-aarch64/Dockerfile, packages/appimage/dockerfile-x86_64/Dockerfile, packages/archlinux/PKGBUILD, packages/debian/control
* Migrate AppImage build environment from Python’s “manylinux” to upstream distro.
* AArch64 build has less external dependencies by using Qt 5.12 (which is incompatible with manylinux_2_28) instead of Qt 5.15.
* Bundle [Alacritty terminal](https://github.com/alacritty/alacritty) in AppImage package.
* Fix terminal determination logic, and adapt it to AppImage change.
* Breaking change: customized terminal path like `qterminal` (search in PATH) or `./qterminal` (relative to cwd) was directly passed to `exec`, while now treated as relative path to `RedPandaIDE`.
* Add more compatible terminals to the lookup list. Almost all terminals listed in [Arch Wiki](https://wiki.archlinux.org/title/List_of_applications/Utilities#Terminal_emulators) was tested.
* Remove build dependency of libicu.
* …
=> Linux package: bundled terminal in AppImage and minor adjustment

RedPandaIDE/main.cpp
MacOS uses high DPI pixmaps with devicePixelRatio equals 2. Setting a flag in QApplication can enforce this in pixmaps fetched from QIcons and thus make the icons look high DPI.
Before: 
After:
=> fix: macos icon size overgrown

RedPandaIDE/systemconsts.h
by RigoLigo, 不过他似乎一直没时间提交, 我就代为提交一下吧...mac的定义中缺少一个consolepauser的常量定义
=> Update systemconsts.h for MacOS

RedPandaIDE/RedPandaIDE.pro, RedPandaIDE/colorschemes/Adaptive.scheme, RedPandaIDE/editor.cpp, RedPandaIDE/editor.h, RedPandaIDE/main.cpp, RedPandaIDE/mainwindow.cpp, RedPandaIDE/thememanager.cpp, RedPandaIDE/thememanager.h, RedPandaIDE/themes/contrast.json, RedPandaIDE/themes/dark.json, RedPandaIDE/themes/default.json, RedPandaIDE/themes/system.json, RedPandaIDE/translations/RedPandaIDE_pt_BR.ts, RedPandaIDE/translations/RedPandaIDE_zh_CN.ts, RedPandaIDE/translations/RedPandaIDE_zh_TW.ts, RedPandaIDE/utils.cpp, RedPandaIDE/utils.h, RedPandaIDE/widgets/choosethemedialog.cpp, RedPandaIDE/widgets/choosethemedialog.h, RedPandaIDE/widgets/choosethemedialog.ui
* Make "Light" theme truly light under Breeze Dark theme.
* With this fix also expose dark mode support on Windows.
* Add "Auto" (system) theme that follows system style and color.
* Add "Adaptive" color scheme for system theme (using transparent background).
* Add support for transparent background in color schemes.
KDE:
DDE:
=> Uniform look for Red Panda C++ under KDE/DDE

.gitattributes, BUILD.md, BUILD_cn.md, packages/appimage/01-in-docker.sh, packages/appimage/dockerfile-aarch64/Dockerfile, packages/appimage/dockerfile-riscv64/Dockerfile, packages/appimage/dockerfile-x86_64/Dockerfile, packages/archlinux/PKGBUILD, packages/debian/01-in-docker.sh
(The purpose of _emulated native build_ is same as cross build, but the approach is slightly different -- emulated native build uses native toolchains with QEMU user space emulation, while cross build uses cross toolchains running natively on host.)
* Fix AppImage emulated native build by replacing `appimagetool.AppImage`, which is incompatible with QEMU user emulation, with `mksquashfs` and `dd`.
* Port AppImage to RISC-V (riscv64).
* Enable RISC-V in Arch Linux package.
* Add a convenient script to build “deb” packages in container for multiple Debian/Ubuntu architectures and versions.
=> Linux package: fix AppImage emulated native build and add RISC-V support

BUILD.md, BUILD_cn.md, RedPandaIDE/widgets/ojproblempropertywidget.h, packages/windows/vcpkg-win7-2023.08.09.patch, tools/astyle/ASLocalizer.cpp, tools/astyle/astyle_main.cpp, tools/consolepauser/consolepauser.pro, tools/consolepauser/main.windows.cpp, tools/redpanda-win-git-askpass/main.cpp
Fix:
- Mismatched class-key in RedPandaIDE (MSVC linker error).
- consolepauser qmake project (MSVC runtime crash).
- Mismatched case in `#include <windows.h>` in astyle (cross MinGW on Linux preprocessor error).
- Format string security in consolepauser (Arch Linux MinGW compiler error).
Add detailed build instructions for:
- MSYS2 Qt library + MinGW toolchain;
- Qt.io Qt library + MinGW or MSVC toolchain;
- vcpkg Qt static library + MSVC toolchain.
=> Fix build failure for various Windows toolchains and update Windows build doc

RedPandaIDE/compiler/compilermanager.cpp, RedPandaIDE/defaultconfigs.qrc, RedPandaIDE/resources/terminal-unix.json, RedPandaIDE/resources/terminal-windows.json, RedPandaIDE/settings.cpp, RedPandaIDE/settings.h, RedPandaIDE/settingsdialog/environmentprogramswidget.cpp, RedPandaIDE/settingsdialog/environmentprogramswidget.h, RedPandaIDE/settingsdialog/environmentprogramswidget.ui, RedPandaIDE/translations/RedPandaIDE_pt_BR.ts, RedPandaIDE/translations/RedPandaIDE_zh_CN.ts, RedPandaIDE/translations/RedPandaIDE_zh_TW.ts, RedPandaIDE/utils.cpp, RedPandaIDE/utils.h
- custom terminal on Windows now require explicit enablement
- customizable terminal arguments pattern and its auto detection
- move hard-coded terminals to resource files
=> Improve custom terminal settings

RedPandaIDE/compiler/compilermanager.cpp, RedPandaIDE/debugger.cpp, RedPandaIDE/mainwindow.cpp, RedPandaIDE/resources/terminal-unix.json, RedPandaIDE/resources/terminal-windows.json, RedPandaIDE/settings.cpp, RedPandaIDE/utils.cpp, packages/appimage/01-in-docker.sh, packages/appimage/dockerfile-aarch64/Dockerfile, packages/appimage/dockerfile-riscv64/Dockerfile, packages/appimage/dockerfile-x86_64/Dockerfile
- Fix some build error and logic error.
- Remove Alacritty from AppImage.
- Alacritty was added to AppImage as a fallback terminal.
- Now that we support almost all popular terminals for Linux, a fallback terminal is no longer required.
- Limit `%*APP_DIR*%` trick to Windows.
- Multiple editions on Linux/macOS shares the same configuration file, and APP_DIR is not reliable.
- Implement Windows search path following `CreateProcessW`.
=> Terminal arguments fix and cleanup

RedPandaIDE/widgets/codecompletionpopup.cpp, RedPandaIDE/widgets/codecompletionpopup.h
On ibus committing a string:
- Red Panda C++ accepts the string and then
- pops up code completion window and
- set focus to `CodeCompletionPopup::mListView`
With the change of focus, ibus commits the preedit string again, which (currently) leads to double lock on a mutex and of course crash, or (if double lock gets fixed) redundant input.
<hr>
Translations for SEO for CJK developers who may encounter similar problems:
当焦点改变时，ibus 再次提交当前的 preedit 内容，导致（当前的实现）重复锁定同一个 mutex 进而崩溃，或者（重复锁定问题修复后）重复输入。
フォーカスが変更されると、ibus はプリエディット文字列を再度コミットします。これにより、(現時点では) ミューテックスが二重ロックされ、当然クラッシュするか、(二重ロックが修正された場合は) 冗長入力が発生します。
포커스가 변경되면 ibus는 사전 편집 문자열을 다시 커밋합니다. 이로 인해 (현재) 뮤텍스에 대한 이중 잠금이 발생하고 물론 충돌이 발생하거나 (이중 잠금이 수정된 경우) 중복 입력이 발생합니다.
=> Fix ibus focus losing behavior

.gitattributes, BUILD.md, BUILD_cn.md, RedPandaIDE/RedPandaIDE.pro, RedPandaIDE/compiler/executablerunner.h, RedPandaIDE/editor.cpp, RedPandaIDE/main.cpp, RedPandaIDE/mainwindow.cpp, RedPandaIDE/parser/cpppreprocessor.cpp, RedPandaIDE/parser/parserutils.h, RedPandaIDE/settingsdialog/environmentfileassociationwidget.cpp, RedPandaIDE/settingsdialog/environmentfileassociationwidget.h, RedPandaIDE/utils.cpp, RedPandaIDE/utils.h, libs/qsynedit/qsynedit.pro, libs/qsynedit/qsynedit/miscprocs.h, libs/redpanda_qt_utils/redpanda_qt_utils.pro, packages/windows/build-qt5.6-mingw-static.sh, packages/windows/qtbase-5.6.3-redpanda.patch, tools/consolepauser/consolepauser.pro
- Changes related to Qt:
- Backport APIs used by Red Panda C++ to Qt 5.6;
- Workaround in Red Panda C++ for `QFile::open(NewOnly)` (too many changes required to backport).
- Changes related to Win32:
- Switch registry APIs to Windows XP-compatible Unicode APIs.
=> Add Windows XP support

.gitattributes, .github/workflows/build.yml, .gitignore, BUILD.md, BUILD_cn.md, packages/alpine/01-in-docker.sh, packages/alpine/APKBUILD.in, packages/alpine/buildapk.sh, packages/archlinux/01-in-docker.sh, packages/archlinux/PKGBUILD.in, packages/archlinux/buildpkg.sh, packages/fedora/01-in-docker.sh, packages/fedora/buildrpm.sh, packages/fedora/redpanda-cpp-git.spec.in, packages/opensuse/01-in-docker.sh, packages/opensuse/buildrpm.sh, packages/opensuse/redpanda-cpp-git.spec.in, tools/astyle/astyle_main.cpp
- Update Arch Linux dependencies.
- Remove “git magic” from Arch Linux and RPM packaging. (Now use `git archive` to generate tarball for build system instead.)
- Fix build error with musl libc.
- Add packaging script and CI for Alpine Linux.
=> Update Linux packaging

RedPandaIDE/debugger.cpp, RedPandaIDE/debugger.h, RedPandaIDE/resources/terminal-unix.json, RedPandaIDE/resources/terminal-windows.json
- Update debugger to respect args pattern.
- Fix `gnome-terminal` pattern for debugging.
- Add pattern for ConEmu.
=> Update terminal arguments pattern

.github/workflows/feature-matrix.yml, .gitignore, BUILD.md, BUILD_cn.md, RedPandaIDE/RedPandaIDE.pro, RedPandaIDE/settings.cpp, RedPandaIDE/settingsdialog/projectversioninfowidget.cpp, RedPandaIDE/utils.cpp, RedPandaIDE/xmake.lua, libs/lua/xmake.lua, libs/qsynedit/xmake.lua, libs/redpanda_qt_utils/qt_utils/utils.cpp, libs/redpanda_qt_utils/xmake.lua, tools/astyle/xmake.lua, tools/consolepauser/xmake.lua, tools/redpanda-git-askpass/xmake.lua, tools/redpanda-win-git-askpass/xmake.lua, xmake.lua
- xmake generating compilation database (`compile_commands.json`) makes it easier to work with various editors/IDEs.
- xmake makes feature matrix test much easier.
- Current status:
- Compilation database generation: seems to work on all platforms.
- Full build: only works with Linux system libs and Windows MSVC dynamic libs.
=> Add xmake as alternative build system

RedPandaIDE/settingsdialog/environmentappearancewidget.ui
修改`EnvironmentAppearanceWidget`的UI，限制“字体大小”最小设置为5。
这么做是因为这种情况下往往是用户设置错了，然后用户会因为文字过小看不见界面而无法撤销更改(主要是我自己遇到过)
修改`RedPandaIDE/settingsdialog/environmentappearancewidget.ui`，为QSpinBox添加minimum属性
=> enhancement: 限制字体大小不得小于5

RedPandaIDE/mainwindow.cpp, RedPandaIDE/translations/RedPandaIDE_pt_BR.ts, RedPandaIDE/translations/RedPandaIDE_zh_CN.ts, RedPandaIDE/translations/RedPandaIDE_zh_TW.ts
修复了重命名文件后'文件名无效'窗口缺失中文翻译的问题，具体情况如下图：
定位到弹窗是在重命名的编辑状态结束后触发，来源于QFileSystemModel库的内部
阅读qt源代码：
qfilesystemmodel.cpp:861
```cpp
static void displayRenameFailedMessage(const QString &newName)
{
#if QT_CONFIG(messagebox)
const QString message =
QFileSystemModel::tr("<b>The name \"%1\" cannot be used.</b>"
"<p>Try using another name, with fewer characters or no punctuation marks.")
.arg(newName);
QMessageBox::information(nullptr, QFileSystemModel::tr("Invalid filename"),
message, QMessageBox::Ok);
#else
Q_UNUSED(newName)
#endif // QT_CONFIG(messagebox)
}
```
对于标准库缺少的翻译需要先添加引用，使用QT_TRANSLATE_NOOP宏来补全翻译
所以说在`RedPandaIDE/mainwindow.cpp`添加宏：
```cpp
static const char *Translation[] =
{
QT_TRANSLATE_NOOP("QFileSystemModel", "<b>The name \"%1\" cannot be used.</b><p>Try using another name, with fewer …
```
=> fix: 修复了重命名文件后'文件名无效'窗口缺失中文翻译的问题

RedPandaIDE/mainwindow.cpp, RedPandaIDE/mainwindow.h
修复新建文件后，不会自动选中并且进入重命名状态的BUG
在`RedPandaIDE/mainwindow.cpp:4524`
```cpp
file.close();
QModelIndex newIndex = mFileSystemModel.index(dir.filePath(fileName));
connect(&mFileSystemModel,&QFileSystemModel::directoryLoaded,
this,&MainWindow::onFilesViewCreateFolderFolderLoaded);
ui->treeFiles->expand(index);
mFilesViewNewCreatedFile=mFileSystemModel.filePath(newIndex);
```
在`RedPandaIDE/mainwindow.h`新定义`QString mFilesViewNewCreatedFile;`
并且在`onFilesViewCreateFolderFolderLoaded`添加了对`mFilesViewNewCreatedFile`的判断
也就是采用了和新建文件夹一样的等待刷新方法
(如果采用`mFileSystemModel.setRootPath(mFileSystemModel.rootPath());`的方法大部分情况下也能正常刷新，但是如果用户创建了一个文件夹，并且这个文件夹是第一次创建，并且文件夹处于未展开状态，那么就会导致新建的文件无法被选中。如果采用和新建文件夹一样的方法就不会有这个问题)
=> fix: 修复了新建文件无法进入选择状态和重命名状态的BUG

RedPandaIDE/translations/RedPandaIDE_zh_CN.ts
This PR updates the Chinese translation for "Goto Page Start and Select" to accurately reflect the functionality of the feature. 
本次PR更新了“Goto Page Start and Select”的中文翻译，以准确反映该功能的操作。
=> Updated the Chinese translation for "Goto Page Start and Select"

platform/windows/installer-scripts/redpanda.nsi
- It is based on an unsound assumption that apps installation/uninstallation are stack-like.
- Setting default app in registry does not work since Windows 8.
=> Do not restore file associations in uninstaller

tools/consolepauser/main.windows.cpp
It was no-op. The last byte of the buffer is '\0'.
=> Fix Windows consolepauser GetErrorMessage

packages/debian-static/builddeb.sh
Hello.
packages/debian-static/builddeb.sh returned this error:
```
dpkg-deb: error: control directory has bad permissions 777 (must be
> >=0755 and <=0775)
```
The fix is simple
`mkdir -m 755 -p "$TMP_FOLDER/DEBIAN"`
I built and installed the IDE
=> Fix debian-static build script

RedPandaIDE/translations/RedPandaIDE_pt_BR.ts, RedPandaIDE/translations/RedPandaIDE_zh_CN.ts, RedPandaIDE/translations/RedPandaIDE_zh_TW.ts, RedPandaIDE/widgets/aboutdialog.cpp
Visual Studio 2022 17.10 came out with MSVC v14.40 (1940), violating versioning rules described in [the document](https://learn.microsoft.com/en-us/cpp/overview/compiler-versions?view=msvc-170).
> Visual Studio 2017 and later
> - For major releases, the minor version increases by 10.
> - For minor releases, the minor version increases by 1 starting with Visual Studio 2017 version 15.3.
=> Simplify compiler version check in about dialog

RedPandaIDE/resources/colorschemes/One_Dark.scheme
按照VSCode原版One Dark Pro调整当前高亮单词、活动断点、选中文字、空格字符、整数、2级括号，错误、警告下划线，取消函数加粗和预处理指令、关键字斜体。实现所有元素全面复刻原版One Dark Pro（对于代码折叠线、1级括号等模棱两可部分仍保留天依蓝设计）。
旧版：
新版：
至于为什么天依蓝处会显示预处理指令和关键字斜体，这其实是One Dark Theme的一个bug，只要曾经安装过One Dark Theme，所有配色的预处理指令和关键字都会变成斜体，可见https://github.com/one-dark/vscode-one-dark-theme/issues/50
=> Adjust color scheme One Dark

.github/workflows/build.yml, BUILD.md, BUILD_cn.md, packages/msys/build-xp.sh, packages/xmingw/build-xp.sh
- upgrade to Qt 5.15.15, mingw-lite 14.2.0
- port bundled mingw-builds to Windows 2000
- previous winxp build now becomes win2000 build, replacing old win2000 build
- automatic dependency download & install
- add cross build script
=> Update Windows legacy packaging script

RedPandaIDE/translations/RedPandaIDE_zh_TW.ts
大约两年前由我负责 小熊猫C++繁体中文 的翻译任务，但是由于一些原因导致进度过慢，加上小熊猫语言文件改动较大，后续导致项目搁浅。现在我打算开始重新翻译。期间如果 ts 文件发生改动，则会立即同步并 pr 一次以保证翻译的 ts 文件中条目是最新的。
---
这个工作量比较大，所以周期较长，望理解。本次 pr 只修改了一点点，表明翻译工作的开始。
=> 更新 zh_TW 翻译文件

RedPandaIDE/RedPandaIDE.pro, RedPandaIDE/settingsdialog/environmentappearancewidget.cpp, RedPandaIDE/translations/RedPandaIDE_ru_RU.ts
Note: In some configurations (half of Windows and AppImage), the assembly failed due to the connection of the qtbase_ru_RU.qm file (apparently, this file is simply not present on these configurations). Temporarily removed this file from the RedPandaIDE.pro and now the build check on all architectures is fine.
=> Add russian interface localization

.github/workflows/feature-matrix.yml, RedPandaIDE/RedPandaIDE.pro, RedPandaIDE/settings.cpp, RedPandaIDE/xmake.lua, Red_Panda_CPP.pro, docs/detailed-build-xdg-cn.md, docs/detailed-build-xdg.md, packages/archlinux/PKGBUILD.in, tools/consolepauser/consolepauser.pro, tools/redpanda-git-askpass/redpanda-git-askpass.pro, xmake.lua
Reinterpret `LIBEXECDIR` as "relative to `PREFIX`", so we can directly use relative path, not calculate from `PREFIX` and `LIBEXECDR`.
=> Remove use of `PREFIX` from XDG program

.github/workflows/build.yml, RedPandaIDE/addon/luaapi.cpp, RedPandaIDE/utils.cpp, addon/defs/global_env.d.tl, docs/detailed-build-win-cn.md, docs/detailed-build-win.md, platform/windows/installer-scripts/utils.nsh
- Deprecate Windows 10
- Lack of usage; no test environment.
- Remove ARM64EC ABI
- Was added for uncertainty of add-on tech, and x64 IME support. Now add-on will based on scripting language, and IMEs have good support for ARM64.
- Deprecate ARM32
- Lack of usage; dropped by hardware, OS, and libraries.
=> Simplify Windows on ARM support

RedPandaIDE/compiler/compilerinfo.cpp, RedPandaIDE/settings.cpp, RedPandaIDE/translations/RedPandaIDE_pt_BR.ts, RedPandaIDE/translations/RedPandaIDE_ru_RU.ts, RedPandaIDE/translations/RedPandaIDE_zh_CN.ts, RedPandaIDE/translations/RedPandaIDE_zh_TW.ts
- Option "Stack Size" renamed to "PE Stack Size" and made available on all host.
- Modify compiler dection logic to set stack size for PE.
=> Fix stack size option for cross toolchain

RedPandaIDE/widgets/searchdialog.ui, RedPandaIDE/widgets/searchinfiledialog.ui
Hi! Thanks for providing so excellent an IDE! I'm finding it extremely useful for me, especially the Competitive Companion integration. 
If you select a lot of code, then press `Ctrl+R/F`, or select `Search -> Replace.../Find...`, the selected text will be filled into the new window, but wrongly expanding the window to be **VERY VERY** wide, and making subsequent callings for this function have the same problem. The only solution seems to be restarting the application.
I set a maximize limit to the dialog widget, and finding it works well. The width limit is currently 2x of the original size 609, and maybe a better limit should be adjusted properly? More discussions are welcome.
您好！感谢您提供了如此优秀的IDE！它对我非常有用，特别是 Competitive Companion 的集成功能。
如果我选中大量代码，然后按下 `Ctrl+R/F` 或选择 `查找 -> …
=> fix: Selecting too long causes the search dialog too wide for the screen to display

RedPandaIDE/settingsdialog/editorsnippetwidget.cpp
=> 修复GASFileTemplate中代码不着色的情况

.github/workflows/build.yml, .github/workflows/feature-matrix.yml
In GitHub Action, windows-2019 has been out of support.
This Pull updates Action File, using windows-2022 to install Visual Studio 2019 and build.
=> Update Build System

RedPandaIDE/mainwindow.cpp
Due to not updating the appearance of the Editor Tab Bar during the appearance update, its appearance is incorrect in Qt6. 
The original code can run very miraculously in Qt5.
=> - bug fix: The appearance of EditorTabBar is incorrect in Qt6
